"""
Django settings for config project.

Generated by 'django-admin startproject' using Django.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h!g22_b^t+ze=yhnbi3%xc2!t1i8f%=h$@w1b4z9(x9o9_cjn5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Adições do Sistema Financeiro ---
    'corsheaders',       # Permite requisições do Frontend (Next.js)
    'ninja',             # Framework da API (FastAPI-like para Django)
    'financeiro_core',   # Nosso app de gestão financeira (Backend)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <--- OBRIGATÓRIO: Deve ser o primeiro!
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuração de CORS (Cross-Origin Resource Sharing)
# Permite que o frontend (Next.js) rodando na porta 3000 acesse o backend na porta 8000
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 1. Banco do NOVO Sistema (Financeiro)
    # O Django gerencia este banco totalmente (tabelas, migrações).
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'financeiro_db',
        'USER': 'postgres',        # Seu usuário local
        'PASSWORD': '96835967@Luck', # <--- SUA SENHA JÁ PREENCHIDA
        'HOST': 'localhost',
        'PORT': '5432',
    },
    
    # 2. Cópia do Banco de Produção (Vendas)
    # Usado apenas para LEITURA. O Router protege contra escritas.
    'vendas_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'loja_producao_backup',
        'USER': 'postgres',        # Seu usuário local
        'PASSWORD': '96835967@Luck', # <--- SUA SENHA JÁ PREENCHIDA
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Router para proteger o banco de vendas contra escritas acidentais
# Garante que o Django nunca tente criar tabelas no 'vendas_db'
DATABASE_ROUTERS = ['config.db_routers.VendasRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'