# Generated by Django 6.0.1 on 2026-01-20 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_contabil', models.CharField(blank=True, max_length=20, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bradesco Loja Centro', max_length=100)),
                ('banco_codigo', models.CharField(blank=True, max_length=10)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('conta', models.CharField(blank=True, max_length=30)),
                ('loja_id_externo', models.IntegerField(db_index=True, verbose_name='ID da Loja (Sistema Vendas)')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTaxaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Contrato Stone 2024', max_length=100)),
                ('loja_id_externo', models.IntegerField(verbose_name='ID da Loja (Sistema Vendas)')),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('tabela_afetada', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id_externo', models.IntegerField(db_index=True)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('faturamento_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_taxas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receita_liquida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_despesas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('resultado_operacional', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('data_fechamento', models.DateTimeField(auto_now=True)),
                ('dados_auditoria_snapshot', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('loja_id_externo', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('loja_id_externo', models.IntegerField(db_index=True, verbose_name='ID da Loja')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('data_competencia', models.DateField(help_text='Mês de referência (Regime de Competência)')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PREVISTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro_core.categoriadespesa')),
                ('conta_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro_core.contabancaria')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro_core.fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='TaxaMaquininha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO_AVISTA', 'Crédito à Vista'), ('CREDITO_PARCELADO', 'Crédito Parcelado'), ('PIX', 'Pix (Maquininha)')], max_length=20)),
                ('bandeira', models.CharField(default='GERAL', help_text='Visa, Master, Elo ou GERAL', max_length=20)),
                ('parcela_inicial', models.IntegerField(default=1)),
                ('parcela_final', models.IntegerField(default=1)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, help_text='Ex: 1.50 para 1.5%', max_digits=5)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dias_para_recebimento', models.IntegerField(default=1)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas', to='financeiro_core.perfiltaxacartao')),
            ],
            options={
                'unique_together': {('perfil', 'tipo', 'bandeira', 'parcela_inicial', 'parcela_final')},
            },
        ),
    ]
