# Generated by Django 6.0.1 on 2026-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriadespesa",
            name="grupo_contabil",
            field=models.CharField(
                choices=[
                    ("IMPOSTOS", "Impostos (Deduções da Receita)"),
                    ("CUSTOS", "Custos de Serviço/Produto"),
                    ("PESSOAL", "Despesas com Pessoal"),
                    ("ADMINISTRATIVA", "Despesas Administrativas"),
                    ("MARKETING", "Vendas e Marketing"),
                    ("FINANCEIRA", "Despesas Financeiras (Taxas, Juros)"),
                ],
                default="ADMINISTRATIVA",
                max_length=50,
            ),
        ),
    ]
