# Generated by Django 6.0.1 on 2026-04-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro_core", "0002_categoriadespesa_grupo_contabil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contapagar",
            name="criado_por",
        ),
        migrations.AddField(
            model_name="contapagar",
            name="criado_por_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID do usuário no banco legado (vendas)",
                null=True,
            ),
        ),
    ]
