# Generated by Django 6.0.1 on 2026-04-10 02:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro_core", "0003_remove_contapagar_criado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contabancaria",
            name="saldo_inicial",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CAIXA_FISICO", "Caixa Físico"),
                    ("CONTA_CORRENTE", "Conta Corrente"),
                    ("POUPANCA", "Poupança"),
                ],
                default="CONTA_CORRENTE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MovimentacaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada de Recursos"),
                            ("SAIDA", "Saída de Recursos"),
                            ("TRANSFERENCIA_SAIDA", "Transferência - Origem"),
                            ("TRANSFERENCIA_ENTRADA", "Transferência - Destino"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Motivo ou descrição do lançamento", max_length=255
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "data_ocorrencia",
                    models.DateTimeField(help_text="Data e hora reais da movimentação"),
                ),
                ("loja_id_externo", models.IntegerField(db_index=True)),
                ("criado_por_id", models.IntegerField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_caixa",
                        to="financeiro_core.categoriadespesa",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="financeiro_core.contabancaria",
                    ),
                ),
                (
                    "despesa_vinculada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagamentos_caixa",
                        to="financeiro_core.contapagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Caixa",
                "verbose_name_plural": "Movimentações de Caixa",
            },
        ),
    ]
