# Generated by Django 6.0.1 on 2026-07-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financeiro_core",
            "0004_contabancaria_saldo_inicial_contabancaria_tipo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contapagar",
            name="data_vencimento",
        ),
        migrations.RemoveField(
            model_name="contapagar",
            name="status",
        ),
        migrations.AddField(
            model_name="contapagar",
            name="data_transacao",
            field=models.DateField(
                blank=True,
                help_text="Data real em que o dinheiro saiu da conta",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RateioDespesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro_core.categoriadespesa",
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="financeiro_core.contapagar",
                    ),
                ),
            ],
        ),
    ]
