# Generated by Django 6.0.1 on 2026-08-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_core', '0005_remove_contapagar_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='descricao_original_extrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='ofx_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='ofx_fitid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='origem_lancamento',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('OFX', 'Extrato OFX/OFC')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='vendedor_id_externo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='vendedor_nome_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rateiodespesa',
            name='vendedor_id_externo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rateiodespesa',
            name='vendedor_nome_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.UniqueConstraint(condition=models.Q(('ofx_fitid__isnull', False)), fields=('conta_origem', 'ofx_fitid'), name='uniq_conta_ofx_fitid'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.UniqueConstraint(condition=models.Q(('ofx_fingerprint__isnull', False)), fields=('conta_origem', 'ofx_fingerprint'), name='uniq_conta_ofx_fingerprint'),
        ),
    ]
